const fs = require('fs');
const path = require('path');
const child_process = require('child_process');

function readTable(fn, reversed) {
  const m = {};
  const s = fs.readFileSync(fn).toString();
  for (const line of s.split(/\r?\n/)) {
    if (line.length === 0 || line.startsWith('#'))
      continue;
    const p = line.match(/^0x([0-9a-f]+)\s+0x([0-9a-f]+)$/i);
    if (!p)
      throw 'Invalid line format: ' + line;
    const i = reversed ? 2 : 1;
    m[parseInt(p[i], 16)] = parseInt(p[3 - i], 16);
  }
  return m;
}

function buildPatch() {
  child_process.execFileSync('tar', ['-C', __dirname, '-xjf', path.join(__dirname, 'big5data.tar.bz2')]);

  const b2uOrig = readTable(path.join(__dirname, 'uao250-b2u.big5.txt'), false);
  const u2bOrig = readTable(path.join(__dirname, 'uao250-u2b.big5.txt'), true);

  const td = new TextDecoder('big5');
  const b2uInit = new Uint16Array(65536);
  const u2bInit = new Uint16Array(65536);

  const chunk = new Uint8Array(2);
  for (let hi = 0x81; hi <= 0xfe; hi++) {
    chunk[0] = hi;
    for (let lo = 0x40; lo <= 0xfe; lo++) {
      if (lo > 0x7e && lo < 0xa1) continue;
      chunk[1] = lo;
      const s = td.decode(chunk);
      if (s.length === 1 && s !== '\ufffd') {
        const u = s.charCodeAt(0);
        const b = (hi << 8) | lo;
        b2uInit[b] = u;
        u2bInit[u] = b;
      }
    }
  }

  // Calculate b2u delta
  const b2uPatch = [];
  for (let b = 0; b < 65536; b++) {
    const origU = b2uOrig[b] || 0;
    if (b2uInit[b] !== origU) {
      b2uPatch.push(b, origU);
    }
  }

  // Apply b2u delta to in-memory tables
  for (let i = 0; i < b2uPatch.length; i += 2) {
    const b = b2uPatch[i];
    const u = b2uPatch[i + 1];
    b2uInit[b] = u;
    if (u) u2bInit[u] = b;
  }

  // Calculate u2b delta (only non-placeholder entries)
  const u2bPatch = [];
  for (let u = 0; u < 65536; u++) {
    const origB = (u2bOrig[u] && u2bOrig[u] < 0xff00) ? u2bOrig[u] : 0;
    if (u2bInit[u] !== origB) {
      u2bPatch.push(u, origB);
    }
  }

  // Clean up extracted files
  child_process.execFileSync('rm', [
    '-f',
    path.join(__dirname, 'uao250-b2u.big5.txt'),
    path.join(__dirname, 'uao250-u2b.big5.txt'),
    path.join(__dirname, 'ambcjk.big5.txt')
  ]);

  // Pack arrays into little-endian binary buffers
  const b2uBuf = Buffer.alloc(b2uPatch.length * 2);
  for (let i = 0; i < b2uPatch.length; i++) {
    b2uBuf.writeUInt16LE(b2uPatch[i], i * 2);
  }

  const u2bBuf = Buffer.alloc(u2bPatch.length * 2);
  for (let i = 0; i < u2bPatch.length; i++) {
    u2bBuf.writeUInt16LE(u2bPatch[i], i * 2);
  }

  const b64B2U = b2uBuf.toString('base64');
  const b64U2B = u2bBuf.toString('base64');

  const patchFile = path.join(__dirname, '..', 'uao_patch.js');
  const content = `// Generated by src/conv/uao/build.js - DO NOT EDIT MANUALLY
// UAO 2.50 delta patches against WHATWG native TextDecoder('big5')
// Packed as little-endian Uint16Array pairs in base64.
// b2uPatch: [big5, unicode] pairs (${b2uPatch.length / 2} entries, ${b2uBuf.length} bytes)
// u2bPatch: [unicode, big5] pairs (${u2bPatch.length / 2} entries, ${u2bBuf.length} bytes)

export const B2U_PATCH =
  '${b64B2U}';

export const U2B_PATCH =
  '${b64U2B}';
`;

  fs.writeFileSync(patchFile, content, 'utf8');
  console.log(`Successfully generated ${patchFile}`);
  console.log(`b2u delta: ${b2uPatch.length / 2} entries (${b2uBuf.length} bytes, base64: ${b64B2U.length} chars)`);
  console.log(`u2b delta: ${u2bPatch.length / 2} entries (${u2bBuf.length} bytes, base64: ${b64U2B.length} chars)`);
}

buildPatch();
