CNAME: 'term.ptt.cc'
TARGET_REPO: 'ptt/term.ptt.cc'
THEME: 'ptt.cc'
APP_TITLE: '批踢踢實業坊'
APP_SHORT_NAME: 'PTT'
APP_DESCRIPTION: '使用網頁版終端機連線至批踢踢實業坊(ptt.cc) -- 以學術性質為目的，提供各專業學生實習的平台，而以電子佈告欄系統為主的一系列服務。期許在網際網路上建立起一個快速、即時、平等、免費，開放且自由的言論空間。'
DYNAMIC_TITLE: 'false'
SITE_URL: 'wss://ws.ptt.cc/bbs'
SITE_TYPE: 'ptt'
DEV_PROXY_TARGET: 'https://ws.ptt.cc'
DEV_PROXY_HEADER: 'https://term.ptt.cc'
