CNAME: 'term.ptt2.cc'
TARGET_REPO: 'ptt/term.ptt2.cc'
THEME: 'ptt2.cc'
PAGE_TITLE: '批踢踢兔'
PAGE_SHORT_NAME: 'PTT2'
PAGE_DESCRIPTION: '批踢踢兔(PTT2)是批踢踢實業坊(ptt.cc)的電子佈告欄服務站之一，主要提供個人看板與團體社團看板，為使用者打造專屬的發表與交流空間。'
DYNAMIC_TITLE: 'false'
DEFAULT_SITE: 'wsstelnet://ws.ptt2.cc/bbs'
SITE_TYPE: 'ptt'
DEV_PROXY_TARGET: 'https://ws.ptt2.cc'
DEV_PROXY_HEADER: 'https://term.ptt2.cc'
