name: Deploy static site

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      TARGET_REPO:
        type: string
        required: true
      CNAME:
        type: string
        required: true
      SITE_URL:
        type: string
        required: true
      DEV_PROXY_TARGET:
        type: string
        required: true
      DEV_PROXY_HEADER:
        type: string
        required: true
      APP_TITLE:
        type: string
        required: false
      APP_SHORT_NAME:
        type: string
        required: false
      APP_DESCRIPTION:
        type: string
        required: false
      THEME:
        type: string
        required: false
      DYNAMIC_TITLE:
        type: string
        required: false
      SITE_TYPE:
        type: string
        required: false
        default: 'auto'
      BRANCH:
        type: string
        required: false
        default: 'gh-pages'
      DEFAULT_PLUGINS:
        type: string
        required: false
        default: ''
    secrets:
      deploy-token:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Install and Build
        run: |
              yarn
              yarn build
              echo "$CNAME" > dist/CNAME
        env:
          CNAME: ${{ inputs.CNAME }}
          APP_THEME: ${{ inputs.THEME }}
          APP_TITLE: ${{ inputs.APP_TITLE }}
          APP_SHORT_NAME: ${{ inputs.APP_SHORT_NAME }}
          APP_DESCRIPTION: ${{ inputs.APP_DESCRIPTION }}
          DYNAMIC_TITLE: ${{ inputs.DYNAMIC_TITLE }}
          SITE_URL: ${{ inputs.SITE_URL }}
          SITE_TYPE: ${{ inputs.SITE_TYPE }}
          DEFAULT_PLUGINS: ${{ inputs.DEFAULT_PLUGINS }}
          ALLOW_OVERRIDE_FROM_QUERY: "yes"
          DEV_PROXY_TARGET: ${{ inputs.DEV_PROXY_TARGET }}
          DEV_PROXY_HEADER: ${{ inputs.DEV_PROXY_HEADER }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          repository-name: ${{ inputs.TARGET_REPO }}
          branch: ${{ inputs.BRANCH }}
          token: ${{ secrets.deploy-token }}
